In [1]:
import scipy.signal

In [2]:
import numpy as np

In [3]:
image_input=np.array([1,2,3,4]) #dim=1, shape=(4,)

In [4]:
filter_h=np.array([4,4,3,2]) # dim=1, shape=(4,)

In [5]:
image_output_scipy=scipy.signal.convolve(image_input,filter_h)

In [6]:
print("Total y(n) generated: {}\ny(n):{}".format(image_output_scipy.shape[0],image_output_scipy))

Total y(n) generated: 7
y(n):[ 4 12 23 36 29 18  8]


In [7]:
image_output=np.zeros([image_input.shape[0]])

In [8]:
filter_h_mirror=np.rot90([filter_h])

In [9]:
filter_h_mirror=filter_h_mirror.reshape([filter_h.shape[0],])#array([2, 3, 4, 4])

In [10]:
filter_h_mirror

array([2, 3, 4, 4])

In [11]:
padded_zeros=(image_input.shape[0]-1)*2
img_out_shape=padded_zeros+image_input.shape[0]
image_padded=np.zeros([img_out_shape,])

In [12]:
for i in range(image_input.shape[0]):
    image_padded[i+3]=image_input[i]

In [13]:
image_padded

array([0., 0., 0., 1., 2., 3., 4., 0., 0., 0.])

In [14]:
image_output=np.zeros([image_input.shape[0]+filter_h.shape[0]-1,])

In [15]:
image_output

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
chunk_counter=0
print("Initial Image_output:{}".format(image_output))
for i in range(image_input.shape[0]+filter_h_mirror.shape[0]-1):
    print("i:{}\n-------".format(i))
    
    arr_chunk=np.zeros([filter_h.shape[0],])
    print("\tChunk_{}:{} ".format(chunk_counter,arr_chunk))
    chunk_counter+=1
    for j in range(i,i+filter_h.shape[0]):
        print("\t\t j:{}".format(j))
        arr_chunk[j-i]=image_padded[j]
    print("\t\t Chunk:{}".format(arr_chunk))
    image_output[i]=np.sum(np.multiply(arr_chunk,filter_h_mirror))
    print("Updated Image:{}".format(image_output))
print(image_output)

Initial Image_output:[0. 0. 0. 0. 0. 0. 0.]
i:0
-------
	Chunk_0:[0. 0. 0. 0.] 
		 j:0
		 j:1
		 j:2
		 j:3
		 Chunk:[0. 0. 0. 1.]
Updated Image:[4. 0. 0. 0. 0. 0. 0.]
i:1
-------
	Chunk_1:[0. 0. 0. 0.] 
		 j:1
		 j:2
		 j:3
		 j:4
		 Chunk:[0. 0. 1. 2.]
Updated Image:[ 4. 12.  0.  0.  0.  0.  0.]
i:2
-------
	Chunk_2:[0. 0. 0. 0.] 
		 j:2
		 j:3
		 j:4
		 j:5
		 Chunk:[0. 1. 2. 3.]
Updated Image:[ 4. 12. 23.  0.  0.  0.  0.]
i:3
-------
	Chunk_3:[0. 0. 0. 0.] 
		 j:3
		 j:4
		 j:5
		 j:6
		 Chunk:[1. 2. 3. 4.]
Updated Image:[ 4. 12. 23. 36.  0.  0.  0.]
i:4
-------
	Chunk_4:[0. 0. 0. 0.] 
		 j:4
		 j:5
		 j:6
		 j:7
		 Chunk:[2. 3. 4. 0.]
Updated Image:[ 4. 12. 23. 36. 29.  0.  0.]
i:5
-------
	Chunk_5:[0. 0. 0. 0.] 
		 j:5
		 j:6
		 j:7
		 j:8
		 Chunk:[3. 4. 0. 0.]
Updated Image:[ 4. 12. 23. 36. 29. 18.  0.]
i:6
-------
	Chunk_6:[0. 0. 0. 0.] 
		 j:6
		 j:7
		 j:8
		 j:9
		 Chunk:[4. 0. 0. 0.]
Updated Image:[ 4. 12. 23. 36. 29. 18.  8.]
[ 4. 12. 23. 36. 29. 18.  8.]
