In [1]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import numpy as np

In [3]:
x_=tf.placeholder(tf.float32,shape=(4,2),name="x_input")

In [4]:
x_inputs=[
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]

In [5]:
#Target output that we know
y_inputs=[
    [0],
    [0],
    [0],
    [1]
]


In [6]:
y_=tf.placeholder(tf.float32,shape=(4,1),name="y_input")

### Defining the weights w in a random fashion

In [7]:
w=tf.Variable(tf.random_uniform([2,1],-1,1),name="weight")

In [8]:
type(x_inputs)


list

In [9]:
type(x_)

tensorflow.python.framework.ops.Tensor

### Defining the base value

In [10]:
b=tf.Variable(tf.zeros([1]),name="Bias")

In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(b.eval())
    print(sess.run(x_,feed_dict={x_:x_inputs}))

[0.]
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [12]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("Printing x_inputs\n----------------------\n {}\n\n".format(sess.run(x_,feed_dict={x_:x_inputs})))
    print("Printing y_outputs (target output)\n---------------------------------\n {}\n\n".format(sess.run(y_,feed_dict={y_:y_inputs})))
    print("Printing b Values:\n--------------------\n {}\n\n".format(b.eval()))
    print("Printing w Values:\n--------------------\n {}\n\n".format(w.eval()))

Printing x_inputs
----------------------
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


Printing y_outputs (target output)
---------------------------------
 [[0.]
 [0.]
 [0.]
 [1.]]


Printing b Values:
--------------------
 [0.]


Printing w Values:
--------------------
 [[ 0.6695485]
 [-0.5784614]]




In [13]:
y_pred=tf.sigmoid(tf.matmul(x_,w)+b)

In [14]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("Printing Y_Predicted:\n-----------------------------\n {}\n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs})))
  

Printing Y_Predicted:
-----------------------------
 [[0.5      ]
 [0.5777701]
 [0.6359243]
 [0.7050252]]




In [15]:
cost=tf.reduce_mean((y_*tf.log(y_pred)+(1.0-y_)*tf.log(1.0-y_pred))*-1)

In [16]:
cost

<tf.Tensor 'Mean:0' shape=() dtype=float32>

In [17]:
learning_rate=0.01

In [18]:
training_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

#### Setup is compleated, now we will go for execution

In [19]:
with tf.Session() as sess:
    writer=tf.summary.FileWriter("./Downloads/AND_W3C1",sess.graph_def)
    dummyCostList=[]
    sess.run(tf.global_variables_initializer())
    #print("Printing hidden layer values (H34):\n............................\n {}\n\n".format(sess.run(h34,feed_dict={x_:x_inputs})))
    
    print("Printing Y_Predicted (Before Training):\n-----------------------------\n {}\n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs})))
    print("Cost Function (Initial):\n--------------------\n{} \n\n".format(sess.run(cost,feed_dict={x_:x_inputs,y_:y_inputs})))
    
    #checking the cost function after each training step
    print("Training (Updating the cost function- minimizing):\n----------------------------------\n")
    for step in range(100000):
        #print(step,end=" ")
        _,loss_val,pred_y,weight,bias=\
            sess.run([training_step,cost,y_pred,w,b],feed_dict={x_:x_inputs,y_:y_inputs})
        #print("Cost/Y_pred/Weight/Bias (Updated @ step {}):\n{}:\n\n{}:\n\n{}:\n\n{}".\
              #format(step,loss_val,pred_y,weight,bias))
        dummyCostList.append(loss_val)
    #print("\n\n")
    print("Final Y_prediction (After Training)\n------------------------\n {} \n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs,y_:y_inputs})))
    print(dummyCostList[-1])
    

Printing Y_Predicted (Before Training):
-----------------------------
 [[0.5       ]
 [0.31221068]
 [0.5005795 ]
 [0.31270862]]


Cost Function (Initial):
--------------------
0.7310525178909302 


Training (Updating the cost function- minimizing):
----------------------------------

Final Y_prediction (After Training)
------------------------
 [[1.2626682e-05]
 [2.0335406e-02]
 [2.0335406e-02]
 [9.7152972e-01]] 


0.01749675


In [20]:
import tensorboard

In [ ]:
# %%cmd
# tensorboard --logdir=./Downloads/AND_W3C1 --host=127.0.0.1