In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
#conda install -c anaconda scikit-learn
from sklearn.datasets import load_boston

In [4]:
def read_infile():
    data=load_boston()
    features=np.array(data.data)
    target=np.array(data.target)
    return features, target

In [5]:
features,target=read_infile()

In [6]:
features[0] #before normalization


array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [7]:
features.shape #means there are 506 houses, each having 13 features.

(506, 13)

In [8]:
target.shape # the target or actual rent of the house

(506,)

In [9]:
def feature_normalize_z_test(data):
    mu=np.mean(data,axis=0)
    std=np.std(data,axis=0)
    return (data-mu)/std

In [10]:
z_features=feature_normalize_z_test(features)

In [11]:
z_features.ndim

2

In [12]:
z_features.shape

(506, 13)

In [13]:
z_features[0] #after normalization

array([-0.41978194,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
        0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
       -1.45900038,  0.44105193, -1.0755623 ])

In [14]:
z_features.shape[0]

506

In [15]:
def append_bias(features,target):
    n_samples=features.shape[0]
    n_features=features.shape[1]
    intercept_feature=np.ones([n_samples,1])
    X=np.concatenate((features,intercept_feature),axis=1) #checkout the np.concatenate documentation for clear understanding
    X=np.reshape(X,[n_samples,n_features+1])
    Y=np.reshape(target,[n_samples,1])
    return X,Y
    

In [16]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [17]:
n_samples=features.shape[0]
n_samples

506

In [18]:
n_features=features.shape[1]
n_features

13

In [19]:
intercept_features=np.ones([n_samples,1])

In [20]:
intercept_features.ndim

2

In [21]:
X=np.concatenate((z_features,intercept_features),axis=1)

In [22]:
print(X[0])

[-0.41978194  0.28482986 -1.2879095  -0.27259857 -0.14421743  0.41367189
 -0.12001342  0.1402136  -0.98284286 -0.66660821 -1.45900038  0.44105193
 -1.0755623   1.        ]


In [23]:
X.shape

(506, 14)

In [24]:
X=np.reshape(X,[n_samples,n_features+1])

In [25]:
X.shape

(506, 14)

In [26]:
a=np.arange(1,10)

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
X_input,Y_input=append_bias(z_features,target)

In [29]:
Y_input.shape

(506, 1)

In [30]:
target.shape

(506,)

In [31]:
X_input.ndim

2

In [32]:
z_features.ndim

2

In [33]:
num_features=X_input.shape[1]

In [34]:
num_features

14