In [3]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [5]:
#Creating a variable
my_var1=tf.Variable([1,2,3])

In [6]:
with tf.Session() as sess:
    sess.run(my_var1.initializer)
    print(my_var1.eval())

[1 2 3]


In [7]:
my_var2=tf.get_variable("vari2",[1,2,3],dtype=tf.int16,initializer=tf.ones_initializer)

In [8]:
with tf.Session() as sess:
    sess.run(my_var2.initializer)
    print(my_var2.eval())

[[[1 1 1]
  [1 1 1]]]


In [9]:
my_var3=tf.Variable([[[1,2,3],[4,5,6]]],dtype=tf.int32)

In [10]:
with tf.Session() as sess:
    sess.run(my_var3.initializer)
    print(my_var3.eval())

[[[1 2 3]
  [4 5 6]]]


In [11]:
my_var4=tf.get_variable("vari4",dtype=tf.int32,initializer=tf.constant([[23,42,12]]))

In [12]:
with tf.Session() as sess:
    sess.run(my_var4.initializer)
    print(my_var4.eval())

[[23 42 12]]


## Using tf.Tensor to use the variables defined using tf.Variable() and tf.get_variable()

In [13]:
my_var5=tf.get_variable("vari5",shape=(),initializer=tf.zeros_initializer())

In [14]:
with tf.Session() as sess:
    sess.run(my_var5.initializer)
    print(my_var5.eval())

0.0


In [15]:
my_var6=tf.get_variable("vari6",initializer=my_var5.initialized_value()+1)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


In [16]:
with tf.Session() as sess:
    sess.run(my_var6.initializer)
    print(my_var6.eval())

1.0


In [17]:
tensor_var1=my_var6+100

In [18]:
with tf.Session() as sess:
    sess.run(my_var6.initializer)
    print(tensor_var1.eval())

101.0


In [19]:
tensor_var1

<tf.Tensor 'add_1:0' shape=() dtype=float32>

In [20]:
my_var6

<tf.Variable 'vari6:0' shape=() dtype=float32_ref>

## To assign value to a variable, use the following methods: (a) assign (b) assign_add

In [21]:
my_var7=tf.get_variable("vari7",shape=(),initializer=tf.zeros_initializer())

In [22]:
with tf.Session() as sess:
    sess.run(my_var7.initializer)
    print(my_var7.eval())

0.0


In [23]:
assignment=my_var7.assign_add(1)

In [24]:
my_var8=tf.get_variable("vari8",shape=(),initializer=tf.zeros_initializer())

### Create a variable my_var9 of 2X2 matrix, initialize it with all one and then assign the following values into it:
[
  [2,2],
  [3,3]
]

In [25]:
my_var9=tf.get_variable("vari9",shape=(2,2),initializer=tf.ones_initializer())

In [26]:
assignment=my_var9.assign([[2,2],[3,3]])

In [27]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    sess.run(assignment)
    print(my_var9.eval())

[[2. 2.]
 [3. 3.]]


In [28]:
with tf.control_dependencies([assignment]):
    w=my_var9.read_value()

In [29]:
with tf.Session() as sess:
    print(w.eval())

[[2. 2.]
 [3. 3.]]


In [30]:
w.shape

TensorShape([Dimension(2), Dimension(2)])

## Sharing variables

In [31]:
#write a function to create a convolutional (Convolution definition, a rolled up or coiled condition)/relu layer (Rectified Linear Units)
def conv_relu(input,kernel_shape,bias_shape):
    #create a varibale named "weights"
    weights=tf.get_variable("weights",kernel_shape,initializer=tf.random_normal_initializer())
    
    #create a varibale named "biases"
    biases=tf.get_variable("biases",bias_shape,initializer=tf.constant_initializer(0.0))
    
    conv_layer=tf.nn.conv2d(input,weights,strides=[1,1,1,1],padding='SAME')
    return tf.nn.relu(conv_layer+biases)

In [32]:
input1=tf.random_normal([1,10,10,32])

In [33]:
with tf.Session() as sess:
    print(input1.eval())

[[[[ 3.43131311e-02 -4.05321687e-01 -5.90873241e-01 ... -4.56055939e-01
    -1.22132719e+00 -2.05250069e-01]
   [-4.59616929e-01 -1.96313471e-01 -1.25102663e+00 ...  8.77759695e-01
    -1.97505403e+00  2.51590699e-01]
   [ 8.63738418e-01 -4.28597718e-01 -2.07657307e-01 ...  1.54526079e+00
    -6.46714270e-02  6.28418803e-01]
   ...
   [ 1.00400008e-01 -5.25533140e-01  4.73670095e-01 ... -5.02709985e-01
    -1.17323494e+00 -1.21407413e+00]
   [ 3.26387808e-02  1.22809374e+00  1.37241638e+00 ...  9.85631347e-01
    -1.15741923e-01 -1.02763534e+00]
   [ 7.43110359e-01 -1.58074409e-01  2.05569744e-01 ... -6.20043874e-02
    -1.03375638e+00 -8.10422719e-01]]

  [[-8.63129258e-01  1.92952144e+00 -3.16795297e-02 ... -9.19104457e-01
    -3.63485277e-01  8.54045570e-01]
   [-6.40225410e-01 -5.48698962e-01  1.26382902e-01 ... -9.66790249e-05
     1.38787127e+00 -2.04575419e+00]
   [-1.70741189e+00  7.23493278e-01 -3.03012133e-01 ...  1.92767441e-01
     1.49886131e-01  1.09965764e-01]
   ...
   

In [34]:
input2=tf.random_normal([1,20,20,32])

In [35]:
x=conv_relu(input1,kernel_shape=[1,1,2,2],bias_shape=[32])

ValueError: Depth of output (2) is not a multiple of the number of groups (16) for '{{node Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](random_normal, weights/read)' with input shapes: [1,10,10,32], [1,1,2,2].

In [37]:
x=conv_relu(x,kernel_shape=[5,5,32,32],bias_shape=[32]) 
#error: Variable weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined

NameError: name 'x' is not defined

In [38]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(x.eval())

NameError: name 'x' is not defined

In [39]:
with tf.variable_scope("conv11"):
    y=conv_relu(input1,kernel_shape=[5,5,32,32],bias_shape=[32])

In [40]:
xx=tf.get_variable("xx",shape=[2,3])

In [41]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(xx.eval())

[[ 0.58743834 -0.9922541   0.0925945 ]
 [-0.8379929   0.9665909   0.9152508 ]]


In [42]:
def my_image_filter(input_image):
    with tf.varibale_scope("conv_scope_3"):
        relu1=conv_relu(input_image,[5,5,32,32],[32])
    with tf.varibale_scope("conv_scope_4"):
        return conv_relu(relu1,[5,5,32,32],[32])
    

In [43]:
input1

<tf.Tensor 'random_normal:0' shape=(1, 10, 10, 32) dtype=float32>

In [44]:
with tf.variable_scope("model"):
    output1=my_image_filter(input1)

AttributeError: module 'tensorflow.compat.v1' has no attribute 'varibale_scope'