In [2]:
import tensorflow as tf

In [3]:
x_=tf.placeholder(tf.float32,shape=(4,2),name="x_input")

In [4]:
x_inputs=[
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]

In [5]:
y_inputs=[
    [0],
    [1],
    [1],
    [0]
]

In [6]:
y_=tf.placeholder(tf.float32,shape=(4,1),name="y_input")

In [7]:
b1=tf.Variable(tf.zeros([2]),name="Bias_1")

In [8]:
b2=tf.Variable(tf.zeros([1]),name="Bias_2")

In [9]:
w1=tf.Variable(tf.random_uniform([2,2],-1,1),name="Weights_1")


In [10]:
w2=tf.Variable(tf.random_uniform([2,1],-1,1),name="Weights_2")

### Printing the initial setup values

In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("Printing x_inputs\n----------------------\n {}\n\n".format(sess.run(x_,feed_dict={x_:x_inputs})))
    print("Printing y_outputs (target output)\n---------------------------------\n {}\n\n".format(sess.run(y_,feed_dict={y_:y_inputs})))
    print("Printing b1 Values:\n--------------------\n {}\n\n".format(b1.eval()))
    print("Printing b2 Values:\n--------------------\n {}\n\n".format(b2.eval()))
    print("Printing w1 Values:\n--------------------\n {}\n\n".format(w1.eval()))
    print("Printing w2 Values:\n--------------------\n {}\n\n".format(w2.eval()))
    x1=x_inputs+b1
    print(x1.eval())

Printing x_inputs
----------------------
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


Printing y_outputs (target output)
---------------------------------
 [[0.]
 [1.]
 [1.]
 [0.]]


Printing b1 Values:
--------------------
 [0. 0.]


Printing b2 Values:
--------------------
 [0.]


Printing w1 Values:
--------------------
 [[-0.6665554   0.8346503 ]
 [ 0.36399174  0.4497769 ]]


Printing w2 Values:
--------------------
 [[ 0.3832655 ]
 [-0.15135407]]


[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


### Generating the predicted output
### Applying the linear activation function insted of non-linear activation function in hidden layer to check the prediction performance

In [19]:
h34=tf.matmul(x_,w1)+b1
#here we are applying linear activation insted of non-linear activation function (sigmoid)
# Main Target is to check how the prediction perform when the activation function is linear

In [20]:
y_pred=tf.sigmoid(tf.matmul(h34,w2)+b2)

In [21]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("Printing hidden layer values (H34):\n............................\n {}\n\n".format(sess.run(h34,feed_dict={x_:x_inputs})))
    print("Printing Y_Predicted:\n-----------------------------\n {}\n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs})))
    

Printing hidden layer values (H34):
............................
 [[ 0.          0.        ]
 [ 0.46105266 -0.9572625 ]
 [ 0.9215796   0.32891488]
 [ 1.3826323  -0.62834764]]


Printing Y_Predicted:
-----------------------------
 [[0.5       ]
 [0.6241586 ]
 [0.37354663]
 [0.4975515 ]]




### Define the Log loss or cross-entropy for updating the cost function 

In [22]:
cost=tf.reduce_mean((y_*tf.log(y_pred)+(1-y_)*tf.log(1.0-y_pred))*-1)
learning_rate=0.01
training_step=tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [24]:
with tf.Session() as sess:
    writer=tf.summary.FileWriter("./Downloads/XOR_logs_final",sess.graph_def)
    sess.run(tf.global_variables_initializer())
    print("Printing hidden layer values (H34):\n............................\n {}\n\n".format(sess.run(h34,feed_dict={x_:x_inputs})))
    print("Printing Y_Predicted (Before Training):\n-----------------------------\n {}\n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs})))
    print("Cost Function (Initial):\n--------------------\n{} \n\n".format(sess.run(cost,feed_dict={x_:x_inputs,y_:y_inputs})))
    
    #checking the cost function after each training step
    print("Training (Updating the cost function- minimizing):\n----------------------------------\n")
    for step in range(100000):
        #print(step,end=" ")
        _,loss_val,pred_y,weight_1,weight_2,bias_1,bias_2=\
            sess.run([training_step,cost,y_pred,w1,w2,b1,b2],feed_dict={x_:x_inputs,y_:y_inputs})
        #print("Cost/Y_pred/Weight1/Weight2/Bias1/Bias2 (Updated @ step {}):\n{}:\n\n{}:\n\n{}:\n\n{}:\n\n{}:\n\n{}".\
              #format(step,loss_val,pred_y,weight_1,weight_2,bias_1,bias_2))
    #print("\n\n")
    print("Final Y_prediction (After Training)\n------------------------\n {} \n\n".format(sess.run(y_pred,feed_dict={x_:x_inputs,y_:y_inputs})))
    

Printing hidden layer values (H34):
............................
 [[ 0.          0.        ]
 [-0.6911986  -0.04774952]
 [-0.32124877  0.76875615]
 [-1.0124474   0.72100663]]


Printing Y_Predicted (Before Training):
-----------------------------
 [[0.5       ]
 [0.6495712 ]
 [0.63907796]
 [0.7664761 ]]


Cost Function (Initial):
--------------------
0.756697416305542 


Training (Updating the cost function- minimizing):
----------------------------------

Final Y_prediction (After Training)
------------------------
 [[0.49999762]
 [0.49999928]
 [0.5000006 ]
 [0.50000215]] 




In [25]:
import tensorboard


In [ ]:
%%cmd
tensorboard --logdir=./Downloads/XOR_logs_final --host=127.0.0.1